---
title: A course on Spatial Data Science
format: "html"
---

::: {.content-visible when-profile='sds4sg'}
The course Spatial Data Science for Social Geography introduces data science and computational analysis
using open source tools written in the Python programming language to the curriculum of
students of geography.

The course is taught in person at Charles University in Prague from October 2023 under the code `MZ340V17`.
:::

::: {.content-visible when-profile='micro'}
The course Spatial Data Science in Python introduces data science and computational analysis
using open source tools written in the Python programming language.

The course is provided by Charles University as a standalone micro-credentials certification and is taught __online__ , typically once a year. The
course is open to anyone.

::: {.callout-important}
# Course registration for 2025 is now open

The first block of classes is scheduled for **September 8 - 12**, and the second block for **September 22 - 26**, each day from 16:00 to 18:00 CEST (Prague time zone). The fee for 2025 is 7,500 CZK (approximately €300). Registration is open until August 31.

Please enroll via the [university portal](https://is.cuni.cz/studium/eng/prijimacky/index.php?do=detail_kurz_mc&cid=11189).

In case of any questions, please contact the course lead directly at [martin.fleischmann@natur.cuni.cz](mailto:martin.fleischmann@natur.cuni.cz).
:::
:::

## Aims

The course supports students with little prior knowledge of core competencies in Spatial Data Science (SDS). It includes:

- Advancing their statistical and numerical literacy.
- Introducing basic principles of programming for data science and state-of-the-art computational tools for SDS.
- Presenting a comprehensive overview of the main methodologies available to the Spatial Data Scientist and their intuition on how and when they can be applied.
- Focusing on real-world applications of these techniques in a geographical and applied context.

::: {.callout-note appearance="simple"}
## What is the scope?

The course revolves around data typically used in human geography, but its applicability
is not limited to human geography. In practice, you will work more with vector
data than rasters (although we cover those a bit as well) and often with data capturing
various aspects of human life. The spatial data science concepts, however, are universal.

:::

## Learning outcomes

After finishing the course, students will be able to:

- Demonstrate understanding of advanced concepts of spatial data science and use the open tools to load and analyze spatial data.
- Understand the motivation and inner logic of the main methodological approaches of open SDS.
- Critically evaluate the suitability of a specific technique, what it can offer, and how it can help answer questions of interest.
- Apply several spatial analysis techniques and explain how to interpret the results in the process of turning data into information.
- Work independently using SDS tools to extract valuable insight when faced with a new dataset.

## Prerequisites

This course assumes an understanding of geography and its key concepts (e.g. coordinate
reference systems or the Modifiable Areal Unit Problem [@openshaw1983modifiable]), at
least basic familiarity with GIS (like file formats and basic spatial data manipulation)
and a basic understanding of statistics (e.g. understanding the concept of regression),
optimally with some spatial component (geographically weighted regression).
While the course will briefly explain these topics, it will not cover the theory and
statistics behind these concepts in detail.

::: {.content-visible when-profile='sds4sg'}
Previous experience in programming or computer science is preferable. A positive attitude towards these topics is essential. In the absence of previous Python experience, the course can be taken, but an increased need for self-study in the first weeks of the semester should be expected.
:::

::: {.content-visible when-profile='micro'}
A basic understanding of Python is required. Understanding of data analysis using `pandas` is not required but certainly helps.
:::

## Course structure


[The material is planned for 12 weeks, with one session per week.]{.content-visible when-profile='sds4sg'}[The material is planned for 2 weeks of teaching 2-hour session per day. There is a one week gap between week 1 and week 2.]{.content-visible when-profile='micro'} Each session
is divided into three parts - _Concepts_, _Hands-on_ and _Exercise_, following the model
proposed by @darribas_gds_course. _Concepts_ have the form of a lecture covering conceptual
aspects of the day's topic, providing necessary theoretical background before digging into code. This part can be nicknamed ["I do"]{.accent}.
_Hands-on_ contains documented code in a Jupyter notebook, executed in
parallel by a lecturer, providing an additional explanation, and by students. Therefore, we have a part ["We do"]{.accent}.
_Exercise_ is a set of tasks to be performed by students individually, with
occasional guidance by the lecturer. So we finish the session with ["You do"]{.accent}.

For enrolled students, the course will finish with a written
assignment in the form of a computational essay. See the
[Assignment](course_information/assignment.qmd) section for details.

## Literature

The course loosely follows the contents of the **Geographic Data Science with Python**
by @rey2023geographic. The online version of the book is available under open access
from [geographicdata.science/book](https://geographicdata.science/book). Using the online
version over the printed one is recommended, although this is entirely up to you.

::: {.callout-note appearance="simple"}

## Spatial or geographic data science?

Spatial data science and geographic data science are often treated as synonyms. In some
interpretations, _spatial_ is broader than _geographic_. In this case, we do _spatial [...]
for [...] geography_, which is, in principle, geographic data science. We will treat
both terms as equal within the context of this course.

:::

## Acknowledgements {.appendix}

The course material is partially derived from
[_A Course on Geographic Data Science_](https://darribas.org/gds_course/) by
@darribas_gds_course and follows its structure, main learning logic, and some
hands-on materials. Thanks, [Dani](https://darribas.org)! A few sections are derived
from other sources acknowledged at the bottom of respective pages. Thank you all!

