<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Spatial Data Science for Social Geography - Regression and geography</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapter_10/exercise.html" rel="next">
<link href="../chapter_10/concepts.html" rel="prev">
<link href="../assets/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../assets/styles.css">
<meta name="twitter:title" content="Spatial Data Science for Social Geography - Regression and geography">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="hands_on_files/figure-html/cell-11-output-1.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapter_10/concepts.html">Regression</a></li><li class="breadcrumb-item"><a href="../chapter_10/hands_on.html">Regression and geography</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../assets/logo.svg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://twitter.com/martinfleis" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/martinfleis/sds" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Search"></div>
</div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_00/infrastructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Infrastructure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_00/assignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_01/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is Spatial Data Science?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_01/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Jupyter and Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_01/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Understanding Notebooks</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Open Data Science</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_02/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Open tools and open mindset</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_02/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_02/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning pandas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Spatial data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_03/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spatial data old and new</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_03/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bring in geography</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_03/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning GeoPandas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Spatial weights</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_04/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Space as math</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_04/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spatial weights in PySAL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_04/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Graph here, graph there</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Exploratory spatial data analysis</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_05/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explore space!</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_05/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spatial autocorrelation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_05/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Does it correlate?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Point patterns</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_06/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">I need more points</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_06/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Point pattern analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_06/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Is there a pattern?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Clustering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_07/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Similar data belong together</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_07/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering and regionalisation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_07/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Find me a cluster</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
 <span class="menu-text">Raster data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_08/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data as a grid</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_08/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Population as a raster grid</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_08/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning xarray</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">
 <span class="menu-text">Interpolation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_09/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Use space in your favour</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_09/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spatial interpolation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_09/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is in between?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">
 <span class="menu-text">Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_10/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Relationship and prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_10/hands_on.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Regression and geography</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_10/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fit that model</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false">
 <span class="menu-text">Machine learning</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_11/concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Is there space in machine learning?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_11/hands_on.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classification and regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_11/exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predict future</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#data" id="toc-data" class="nav-link active" data-scroll-target="#data">Data</a></li>
  <li><a href="#non-spatial-linear-regression" id="toc-non-spatial-linear-regression" class="nav-link" data-scroll-target="#non-spatial-linear-regression">Non-spatial linear regression</a>
  <ul class="collapse">
  <li><a href="#ols-model" id="toc-ols-model" class="nav-link" data-scroll-target="#ols-model">OLS model</a></li>
  <li><a href="#spatial-exploration-of-the-model-hidden-structures" id="toc-spatial-exploration-of-the-model-hidden-structures" class="nav-link" data-scroll-target="#spatial-exploration-of-the-model-hidden-structures">Spatial exploration of the model (hidden structures)</a></li>
  </ul></li>
  <li><a href="#spatial-heterogeneity" id="toc-spatial-heterogeneity" class="nav-link" data-scroll-target="#spatial-heterogeneity">Spatial heterogeneity</a>
  <ul class="collapse">
  <li><a href="#spatial-fixed-effects" id="toc-spatial-fixed-effects" class="nav-link" data-scroll-target="#spatial-fixed-effects">Spatial fixed effects</a></li>
  </ul></li>
  <li><a href="#geographically-weighted-regression" id="toc-geographically-weighted-regression" class="nav-link" data-scroll-target="#geographically-weighted-regression">Geographically weighted regression</a>
  <ul class="collapse">
  <li><a href="#fixed-bandwidth" id="toc-fixed-bandwidth" class="nav-link" data-scroll-target="#fixed-bandwidth">Fixed bandwidth</a></li>
  </ul></li>
  
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/martinfleis/sds/issues/new" class="toc-action">Report an issue</a></p></div></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="hands_on.ipynb" download="hands_on.ipynb"><i class="bi bi-journal-code"></i>Jupyter</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression and geography</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Still in works
</div>
</div>
<div class="callout-body-container callout-body">
<p>This notebook currently requires development versions of <code>mgwr</code> and <code>spglm</code> packages specified in the <a href="../environment.yml">environment file</a>.</p>
</div>
</div>
<p>When trying to determine the effect of some (independent) variables on the outcome of phenomena (dependent variable), you often use regression to model such an outcome and understand the influence each of the variables has in the model. With spatial regression, it is the same. You just need to use the spatial dimension in a mindful way.</p>
<p>This chapter provides an introduction to ways of incorporating space into regression models, from spatial variables in standard linear regression to geographically weighted regression.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> esda</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mgwr</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> sm</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> libpysal <span class="im">import</span> graph</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> splot.esda <span class="im">import</span> lisa_cluster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>You will work with the same data you already used in the chapter on <a href="../chapter_05/hands_on.html">spatial autocorrelation</a> - the results of the second round of the presidential elections in Czechia in 2023, between Petr Pavel and Andrej Babiš, on a level of municipalities. You can read the election data directly from the chapter 5 location.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>elections <span class="op">=</span> gpd.read_file(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://martinfleischmann.net/sds/chapter_05/data/cz_elections_2023.gpkg"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>elections <span class="op">=</span> elections.set_index(<span class="st">"name"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>elections.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">PetrPavel</th>
<th data-quarto-table-cell-role="th">AndrejBabis</th>
<th data-quarto-table-cell-role="th">nationalCode</th>
<th data-quarto-table-cell-role="th">sourceOfName</th>
<th data-quarto-table-cell-role="th">geometry</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Abertamy</td>
<td>62.98</td>
<td>37.01</td>
<td>554979</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-849678.970 -996811.240, -8494...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Adamov (Blansko, 581291)</td>
<td>57.17</td>
<td>42.82</td>
<td>581291</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-590872.420 -1148832.360, -591...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Adamov (České Budějovice, 535826)</td>
<td>65.17</td>
<td>34.82</td>
<td>535826</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-748969.500 -1162820.890, -749...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Adamov (Kutná Hora, 531367)</td>
<td>53.84</td>
<td>46.15</td>
<td>531367</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-677775.470 -1077800.050, -677...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Adršpach</td>
<td>62.18</td>
<td>37.81</td>
<td>547786</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-620084.550 -999987.800, -6201...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Instead of reading the file directly off the web, it is possible to download it manually, store it on your computer, and read it locally. To do that, you can follow these steps:</p>
<ol type="1">
<li>Download the file by right-clicking on <a href="https://martinfleischmann.net/sds/chapter_05/data/cz_elections_2023.gpkg">this link</a> and saving the file</li>
<li>Place the file in the same folder as the notebook where you intend to read it</li>
<li>Replace the code in the cell above with:</li>
</ol>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>elections <span class="op">=</span> gpd.read_file(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"cz_elections_2023.gpkg"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>The election results give you the dependent variable - you will look at the percentage of votes Petr Pavel, the winner, received. From the <a href="../chapter_05/hands_on.html#code-cell-2">map of the results</a> and the analysis you did when exploring spatial autocorrelation you already know that there are some significant spatial patterns. Let’s look whether these patterns correspond to the composition of education levels within each municipality.</p>
<p>You can use the data from the <a href="https://www.czso.cz/csu/czso/vysledky-scitani-2021-otevrena-data">Czech Statistical Office</a> reflecting the situation during the Census 2021. The original table has been <a href="../data/cz_education_2021/preprocessing.html">preprocessed</a> and is available as a CSV.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>education <span class="op">=</span> pd.read_csv(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://martinfleischmann.net/sds/chapter_10/data/education.csv"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>education.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">uzemi_kod</th>
<th data-quarto-table-cell-role="th">without_education</th>
<th data-quarto-table-cell-role="th">undetermined</th>
<th data-quarto-table-cell-role="th">incomplete_primary_education</th>
<th data-quarto-table-cell-role="th">lower_secondary_and_secondary_education</th>
<th data-quarto-table-cell-role="th">further_education</th>
<th data-quarto-table-cell-role="th">post_maturita_studies</th>
<th data-quarto-table-cell-role="th">bachelors_degree</th>
<th data-quarto-table-cell-role="th">doctoral_degree</th>
<th data-quarto-table-cell-role="th">masters_degree</th>
<th data-quarto-table-cell-role="th">higher_vocational_education</th>
<th data-quarto-table-cell-role="th">higher_vocational_education_in_a_conservatory</th>
<th data-quarto-table-cell-role="th">primary_education</th>
<th data-quarto-table-cell-role="th">complete_secondary_vocational_education</th>
<th data-quarto-table-cell-role="th">complete_secondary_general_education</th>
<th data-quarto-table-cell-role="th">okres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>500011</td>
<td>0.570704</td>
<td>3.741281</td>
<td>1.141408</td>
<td>34.242232</td>
<td>1.775523</td>
<td>0.507292</td>
<td>2.853519</td>
<td>0.634115</td>
<td>12.935954</td>
<td>1.395054</td>
<td>0.126823</td>
<td>11.350666</td>
<td>17.945466</td>
<td>10.779962</td>
<td>Zlín</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>500020</td>
<td>0.885827</td>
<td>3.346457</td>
<td>1.968504</td>
<td>40.157480</td>
<td>2.066929</td>
<td>0.885827</td>
<td>1.771654</td>
<td>0.492126</td>
<td>6.299213</td>
<td>1.574803</td>
<td>0.000000</td>
<td>15.059055</td>
<td>16.338583</td>
<td>9.153543</td>
<td>Šumperk</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>500046</td>
<td>0.359195</td>
<td>3.232759</td>
<td>0.790230</td>
<td>39.152299</td>
<td>2.514368</td>
<td>0.790230</td>
<td>3.520115</td>
<td>0.215517</td>
<td>10.632184</td>
<td>1.364943</td>
<td>0.143678</td>
<td>9.770115</td>
<td>15.301724</td>
<td>12.212644</td>
<td>Nový Jičín</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>500062</td>
<td>0.238237</td>
<td>3.573556</td>
<td>1.072067</td>
<td>32.757594</td>
<td>2.084574</td>
<td>1.131626</td>
<td>3.037522</td>
<td>0.178678</td>
<td>13.281715</td>
<td>0.714711</td>
<td>0.119119</td>
<td>11.316260</td>
<td>18.701608</td>
<td>11.792734</td>
<td>Vsetín</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>500071</td>
<td>0.412939</td>
<td>2.890571</td>
<td>1.238816</td>
<td>34.067447</td>
<td>1.720578</td>
<td>0.757054</td>
<td>3.028217</td>
<td>0.137646</td>
<td>11.080523</td>
<td>0.894701</td>
<td>0.000000</td>
<td>9.772884</td>
<td>20.027529</td>
<td>13.971094</td>
<td>Vsetín</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Instead of reading the file directly off the web, it is possible to download it manually, store it on your computer, and read it locally. To do that, you can follow these steps:</p>
<ol type="1">
<li>Download the file by right-clicking on <a href="&quot;https://martinfleischmann.net/sds/chapter_10/data/education.csv&quot;">this link</a> and saving the file</li>
<li>Place the file in the same folder as the notebook where you intend to read it</li>
<li>Replace the code in the cell above with:</li>
</ol>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>education <span class="op">=</span> pd.read_csv(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"education.csv"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>The first thing you need to do is to merge the two tables, to have both dependent and independent variables together. The municipality code in the <code>elections</code> table is in the <code>"nationalCode"</code> column, while in the education table in the <code>"uzemi_kod"</code> column.</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>elections_data <span class="op">=</span> elections.merge(education, left_on<span class="op">=</span><span class="st">"nationalCode"</span>, right_on<span class="op">=</span><span class="st">"uzemi_kod"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>elections_data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">PetrPavel</th>
<th data-quarto-table-cell-role="th">AndrejBabis</th>
<th data-quarto-table-cell-role="th">nationalCode</th>
<th data-quarto-table-cell-role="th">sourceOfName</th>
<th data-quarto-table-cell-role="th">geometry</th>
<th data-quarto-table-cell-role="th">uzemi_kod</th>
<th data-quarto-table-cell-role="th">without_education</th>
<th data-quarto-table-cell-role="th">undetermined</th>
<th data-quarto-table-cell-role="th">incomplete_primary_education</th>
<th data-quarto-table-cell-role="th">lower_secondary_and_secondary_education</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">post_maturita_studies</th>
<th data-quarto-table-cell-role="th">bachelors_degree</th>
<th data-quarto-table-cell-role="th">doctoral_degree</th>
<th data-quarto-table-cell-role="th">masters_degree</th>
<th data-quarto-table-cell-role="th">higher_vocational_education</th>
<th data-quarto-table-cell-role="th">higher_vocational_education_in_a_conservatory</th>
<th data-quarto-table-cell-role="th">primary_education</th>
<th data-quarto-table-cell-role="th">complete_secondary_vocational_education</th>
<th data-quarto-table-cell-role="th">complete_secondary_general_education</th>
<th data-quarto-table-cell-role="th">okres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>62.98</td>
<td>37.01</td>
<td>554979</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-849678.970 -996811.240, -8494...</td>
<td>554979</td>
<td>0.435414</td>
<td>11.030479</td>
<td>1.741655</td>
<td>37.010160</td>
<td>...</td>
<td>1.161103</td>
<td>1.306241</td>
<td>0.290276</td>
<td>5.950653</td>
<td>0.580552</td>
<td>0.00000</td>
<td>21.335269</td>
<td>8.998549</td>
<td>9.579100</td>
<td>Karlovy Vary</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>57.17</td>
<td>42.82</td>
<td>581291</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-590872.420 -1148832.360, -591...</td>
<td>581291</td>
<td>0.377766</td>
<td>5.153805</td>
<td>1.052348</td>
<td>34.592553</td>
<td>...</td>
<td>0.782515</td>
<td>2.725310</td>
<td>1.187264</td>
<td>11.171074</td>
<td>1.349164</td>
<td>0.08095</td>
<td>11.359957</td>
<td>17.539126</td>
<td>11.225040</td>
<td>Blansko</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>65.17</td>
<td>34.82</td>
<td>535826</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-748969.500 -1162820.890, -749...</td>
<td>535826</td>
<td>0.269542</td>
<td>3.234501</td>
<td>0.943396</td>
<td>23.450135</td>
<td>...</td>
<td>0.673854</td>
<td>4.582210</td>
<td>1.482480</td>
<td>23.450135</td>
<td>2.156334</td>
<td>0.00000</td>
<td>7.547170</td>
<td>17.250674</td>
<td>13.477089</td>
<td>České Budějovice</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>53.84</td>
<td>46.15</td>
<td>531367</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-677775.470 -1077800.050, -677...</td>
<td>531367</td>
<td>0.000000</td>
<td>3.508772</td>
<td>1.754386</td>
<td>44.736842</td>
<td>...</td>
<td>0.877193</td>
<td>2.631579</td>
<td>0.000000</td>
<td>5.263158</td>
<td>0.000000</td>
<td>0.00000</td>
<td>7.017544</td>
<td>20.175439</td>
<td>13.157895</td>
<td>Kutná Hora</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>62.18</td>
<td>37.81</td>
<td>547786</td>
<td>Český úřad zeměměřický a katastrální</td>
<td>MULTIPOLYGON (((-620084.550 -999987.800, -6201...</td>
<td>547786</td>
<td>0.744417</td>
<td>8.188586</td>
<td>0.992556</td>
<td>39.702233</td>
<td>...</td>
<td>0.496278</td>
<td>2.729529</td>
<td>0.248139</td>
<td>6.451613</td>
<td>0.000000</td>
<td>0.00000</td>
<td>12.903226</td>
<td>13.895782</td>
<td>12.406948</td>
<td>Náchod</td>
</tr>
</tbody>
</table>

<p>5 rows × 21 columns</p>
</div>
</div>
</div>
<p>That is all sorted and ready to be used in a regression.</p>
</section>
<section id="non-spatial-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="non-spatial-linear-regression">Non-spatial linear regression</h2>
<p>Before jumping into spatial regression, let’s start with the standard linear regression. A useful start is to explore the data using an ordinary least squares (OLS) linear regression model.</p>
<section id="ols-model" class="level3">
<h3 class="anchored" data-anchor-id="ols-model">OLS model</h3>
<p>While this course is not formula-heavy, in this case, it is useful to use the formula to explain the logic of the algorithm. The OLS tries to model the dependent variable <span class="math inline">\(y\)</span> as the linear combination of independent variables <span class="math inline">\(x_1, x_2, ... x_n\)</span>:</p>
<p><span class="math display">\[y_{i}=\alpha+\beta _{1}\ x_{i1}+\beta _{2}\ x_{i2}+\cdots +\beta _{p}\ x_{ip}+\varepsilon _{i}\]</span></p>
<p>where <span class="math inline">\(\epsilon_{i}\)</span> represents unobserved random variables and <span class="math inline">\(\alpha\)</span> represents an intercept - a constant. You know the <span class="math inline">\(y_i\)</span>, all of the <span class="math inline">\(x_i\)</span> and try to estimate the coefficients. In Python, you can run linear regression using implementations from more than one package (e.g., <code>statsmodels</code>, <code>scikit-learn</code>, <code>spreg</code>). This course covers <code>statsmodels</code> approach as it has a nice API to work with.</p>
<p>First, you need a list of names of independent variables. That is equal to column names without a few of the columns that represent other data.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>independent_names <span class="op">=</span> education.columns.drop([<span class="st">"uzemi_kod"</span>, <span class="st">"okres"</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>independent_names</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>Index(['without_education', 'undetermined', 'incomplete_primary_education',
       'lower_secondary_and_secondary_education', 'further_education',
       'post_maturita_studies', 'bachelors_degree', 'doctoral_degree',
       'masters_degree', 'higher_vocational_education',
       'higher_vocational_education_in_a_conservatory', 'primary_education',
       'complete_secondary_vocational_education',
       'complete_secondary_general_education'],
      dtype='object')</code></pre>
</div>
</div>
<p><code>statsmodels</code> (above imported as <code>sm</code>) offers an intuitive formula API to define the linear regression.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="annotated-cell-6"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-6" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-6-1" class="code-annotation-target"><a href="#annotated-cell-6-1" aria-hidden="true" tabindex="-1"></a>formula <span class="op">=</span> <span class="ss">f"PetrPavel ~ </span><span class="sc">{</span><span class="st">' + '</span><span class="sc">.</span>join(independent_names)<span class="sc">}</span><span class="ss">"</span></span>
<span id="annotated-cell-6-2"><a href="#annotated-cell-6-2" aria-hidden="true" tabindex="-1"></a>formula</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-6" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-6">In the formula, specify the dependent variable (<code>"PetrPavel"</code>) as a function of (<code>"~"</code>) independent variables (<code>"undetermined + incomplete_primary_education + ..."</code>).</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>'PetrPavel ~ without_education + undetermined + incomplete_primary_education + lower_secondary_and_secondary_education + further_education + post_maturita_studies + bachelors_degree + doctoral_degree + masters_degree + higher_vocational_education + higher_vocational_education_in_a_conservatory + primary_education + complete_secondary_vocational_education + complete_secondary_general_education'</code></pre>
</div>
</div>
<p>With the formula ready, you can fit the model and estimate all betas and <span class="math inline">\(\varepsilon\)</span>.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ols <span class="op">=</span> sm.ols(formula, data<span class="op">=</span>elections_data).fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>ols</code> object offers a handy <code>summary()</code> function providing most of the results from the fitting in one place.</p>
<div class="cell explore" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ols.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>PetrPavel</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.423</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.422</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>352.6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Mon, 20 Nov 2023</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>22:24:18</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-22397.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>6254</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>4.482e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>6240</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>4.492e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>13</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>0.1283</td>
<td>0.006</td>
<td>19.748</td>
<td>0.000</td>
<td>0.116</td>
<td>0.141</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">without_education</td>
<td>0.3621</td>
<td>0.093</td>
<td>3.914</td>
<td>0.000</td>
<td>0.181</td>
<td>0.543</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">undetermined</td>
<td>0.1879</td>
<td>0.041</td>
<td>4.542</td>
<td>0.000</td>
<td>0.107</td>
<td>0.269</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">incomplete_primary_education</td>
<td>-0.0881</td>
<td>0.119</td>
<td>-0.737</td>
<td>0.461</td>
<td>-0.322</td>
<td>0.146</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">lower_secondary_and_secondary_education</td>
<td>0.2890</td>
<td>0.013</td>
<td>21.435</td>
<td>0.000</td>
<td>0.263</td>
<td>0.315</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">further_education</td>
<td>0.9665</td>
<td>0.116</td>
<td>8.312</td>
<td>0.000</td>
<td>0.739</td>
<td>1.194</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">post_maturita_studies</td>
<td>1.3528</td>
<td>0.204</td>
<td>6.635</td>
<td>0.000</td>
<td>0.953</td>
<td>1.752</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">bachelors_degree</td>
<td>1.1634</td>
<td>0.092</td>
<td>12.581</td>
<td>0.000</td>
<td>0.982</td>
<td>1.345</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">doctoral_degree</td>
<td>1.2223</td>
<td>0.220</td>
<td>5.550</td>
<td>0.000</td>
<td>0.791</td>
<td>1.654</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">masters_degree</td>
<td>1.1231</td>
<td>0.036</td>
<td>31.201</td>
<td>0.000</td>
<td>1.053</td>
<td>1.194</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">higher_vocational_education</td>
<td>1.7312</td>
<td>0.132</td>
<td>13.124</td>
<td>0.000</td>
<td>1.473</td>
<td>1.990</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">higher_vocational_education_in_a_conservatory</td>
<td>2.7664</td>
<td>0.577</td>
<td>4.796</td>
<td>0.000</td>
<td>1.636</td>
<td>3.897</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">primary_education</td>
<td>0.0723</td>
<td>0.033</td>
<td>2.213</td>
<td>0.027</td>
<td>0.008</td>
<td>0.136</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">complete_secondary_vocational_education</td>
<td>0.8683</td>
<td>0.032</td>
<td>27.316</td>
<td>0.000</td>
<td>0.806</td>
<td>0.931</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">complete_secondary_general_education</td>
<td>0.8121</td>
<td>0.038</td>
<td>21.247</td>
<td>0.000</td>
<td>0.737</td>
<td>0.887</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>130.315</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>1.981</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.000</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>215.929</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>0.189</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>1.29e-47</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>3.828</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>5.74e+17</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br>[2] The smallest eigenvalue is 4.03e-29. This might indicate that there are<br>strong multicollinearity problems or that the design matrix is singular.
</div>
</div>
<p>It is clear that education composition has a significant effect on the outcome of the elections but can explain only about 42% of its variance (adjusted <span class="math inline">\(R^2\)</span> is 0.422). A higher amount of residents with only primary education tends to lower Pavel’s gain while a higher amount of university degrees tends to increase the number of votes he received. That is nothing unexpected. However, let’s make use of geography and unpack these results a bit.</p>
</section>
<section id="spatial-exploration-of-the-model-hidden-structures" class="level3">
<h3 class="anchored" data-anchor-id="spatial-exploration-of-the-model-hidden-structures">Spatial exploration of the model (hidden structures)</h3>
<p>Start with the visualisation of the prediction the OLS model produces using the coefficients shown above.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="annotated-cell-9"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-9-1" class="code-annotation-target"><a href="#annotated-cell-9-1" aria-hidden="true" tabindex="-1"></a>predicted <span class="op">=</span> ols.predict(elections_data)</span>
<span id="annotated-cell-9-2"><a href="#annotated-cell-9-2" aria-hidden="true" tabindex="-1"></a>predicted.head()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-9" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-9">Use the <code>predict()</code> method with the original data to get the prediction using the model.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>0    41.731952
1    58.447707
2    73.554706
3    53.281638
4    48.993730
dtype: float64</code></pre>
</div>
</div>
<p>Make a plot comparing the prediction with the actual results.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="annotated-cell-10"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-10-1" class="code-annotation-target"><a href="#annotated-cell-10-1" aria-hidden="true" tabindex="-1"></a>f, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">8</span>))</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-10-2" class="code-annotation-target"><a href="#annotated-cell-10-2" aria-hidden="true" tabindex="-1"></a>elections_data.plot(</span>
<span id="annotated-cell-10-3"><a href="#annotated-cell-10-3" aria-hidden="true" tabindex="-1"></a>    predicted, legend<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">100</span>, ax<span class="op">=</span>axs[<span class="dv">0</span>]</span>
<span id="annotated-cell-10-4"><a href="#annotated-cell-10-4" aria-hidden="true" tabindex="-1"></a>)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-10-5" class="code-annotation-target"><a href="#annotated-cell-10-5" aria-hidden="true" tabindex="-1"></a>elections_data.plot(</span>
<span id="annotated-cell-10-6"><a href="#annotated-cell-10-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PetrPavel"</span>, legend<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">100</span>, ax<span class="op">=</span>axs[<span class="dv">1</span>]</span>
<span id="annotated-cell-10-7"><a href="#annotated-cell-10-7" aria-hidden="true" tabindex="-1"></a>)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-10-8" class="code-annotation-target"><a href="#annotated-cell-10-8" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_title(<span class="st">"OLS prediction"</span>)</span>
<span id="annotated-cell-10-9"><a href="#annotated-cell-10-9" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_title(<span class="st">"Actual results"</span>)</span>
<span id="annotated-cell-10-10"><a href="#annotated-cell-10-10" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-10-11" class="code-annotation-target"><a href="#annotated-cell-10-11" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_axis_off()</span>
<span id="annotated-cell-10-12"><a href="#annotated-cell-10-12" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_axis_off()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-10" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-10">Create a subplot with two axes.</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2,3,4" data-code-cell="annotated-cell-10">Plot the <code>predicted</code> data on the <code>elections_data</code> geometry.</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="3">3</dt>
<dd>
<span data-code-annotation="3" data-code-lines="5,6,7" data-code-cell="annotated-cell-10">Plot the original results.</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="4">4</dt>
<dd>
<span data-code-annotation="4" data-code-lines="8,9" data-code-cell="annotated-cell-10">Set titles for axes in the subplot.</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="5">5</dt>
<dd>
<span data-code-annotation="5" data-code-lines="11,12" data-code-cell="annotated-cell-10">Remove axes borders.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-11-output-1.png" width="510" height="633" class="figure-img"></p>
<figcaption class="figure-caption">OLS prediction and the actual outcome</figcaption>
</figure>
</div>
</div>
</div>
<p>The general patterns are captured but there are some areas of the country which seem to be quite off. The actual error between prediction and the dependent variable is captured as <em>residuals</em>, which are directly available in <code>ols</code> as <code>ols.resid</code> attribute. Let’s plot to get a better comparison.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="annotated-cell-11"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-11-1" class="code-annotation-target"><a href="#annotated-cell-11-1" aria-hidden="true" tabindex="-1"></a>elections_data[<span class="st">"residual"</span>] <span class="op">=</span> ols.resid</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-11-2" class="code-annotation-target"><a href="#annotated-cell-11-2" aria-hidden="true" tabindex="-1"></a>max_residual <span class="op">=</span> ols.resid.<span class="bu">abs</span>().<span class="bu">max</span>()</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-11-3" class="code-annotation-target"><a href="#annotated-cell-11-3" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> elections_data.plot(</span>
<span id="annotated-cell-11-4"><a href="#annotated-cell-11-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residual"</span>, legend<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"RdBu"</span>, vmin<span class="op">=-</span>max_residual, vmax<span class="op">=</span>max_residual</span>
<span id="annotated-cell-11-5"><a href="#annotated-cell-11-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-11-6"><a href="#annotated-cell-11-6" aria-hidden="true" tabindex="-1"></a>ax.set_axis_off()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-11">Assign residuals as a column. This is not needed for the plot but it will be useful later.</span>
</dd>
<dt data-target-cell="annotated-cell-11" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2" data-code-cell="annotated-cell-11">Identify the maximum residual value based on absolute value to specify <code>vmin</code> and <code>vmax</code> values of the colormap.</span>
</dd>
<dt data-target-cell="annotated-cell-11" data-target-annotation="3">3</dt>
<dd>
<span data-code-annotation="3" data-code-lines="3,4,5" data-code-cell="annotated-cell-11">Plot the data using diverging colormap centred around 0.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-12-output-1.png" width="518" height="395" class="figure-img"></p>
<figcaption class="figure-caption">Residuals of the OLS prediction</figcaption>
</figure>
</div>
</div>
</div>
<p>All of the municipalities in blue (residual above 0) have reported higher gains for Petr Pavel than the model assumes based on education structure, while all in red reported lower gains than what is expected. However, as data scientists, we have better tools to analyse the spatial structure of residuals than eyeballing it. Let’s recall the chapter on spatial autocorrelation again and figure out the spatial clusters of residuals.</p>
<p>First, create a contiguity graph and row-normalise it.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>contiguity_r <span class="op">=</span> graph.Graph.build_contiguity(elections_data).transform(<span class="st">"r"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then you can generate a Moran plot of residuals. For that, you will need the lag of residuals.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>elections_data[<span class="st">"residual_lag"</span>] <span class="op">=</span> contiguity_r.lag(elections_data[<span class="st">"residual"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And then you can use the code from the earlier chapter to generate a Moran scatterplot using <code>seaborn</code>.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>f, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">6</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>sns.regplot(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"residual"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"residual_lag"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>elections_data,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    marker<span class="op">=</span><span class="st">"."</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    scatter_kws<span class="op">=</span>{<span class="st">"alpha"</span>: <span class="fl">0.2</span>},</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    line_kws<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span><span class="st">"lightcoral"</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">0</span>, c<span class="op">=</span><span class="st">"black"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, c<span class="op">=</span><span class="st">"black"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-15-output-1.png" width="521" height="503" class="figure-img"></p>
<figcaption class="figure-caption">Moran Plot</figcaption>
</figure>
</div>
</div>
</div>
<p>That looks like a pretty strong relationship. Use the local version of Moran’s statistic to find out the clusters.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="annotated-cell-15"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-15" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-15-1" class="code-annotation-target"><a href="#annotated-cell-15-1" aria-hidden="true" tabindex="-1"></a>lisa <span class="op">=</span> esda.Moran_Local(elections_data[<span class="st">'residual'</span>], contiguity_r.to_W())</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-15" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-15">Use <code>Moran_Local</code> function from <code>esda</code> and remember that it needs <code>W</code>, not <code>Graph</code>.</span>
</dd>
</dl>
</div>
</div>
<p>Let’s use our handy <code>lisa_cluster</code> function from <code>splot</code> to visualise the results.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> lisa_cluster(lisa, elections_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-17-output-1.png" width="540" height="341" class="figure-img"></p>
<figcaption class="figure-caption">LISA clusters</figcaption>
</figure>
</div>
</div>
</div>
<p>The outcome of LISA shows large clusters of both overpredicted (high-high) and underpredicted (low-low) areas. The underpredicted are mostly in central Bohemia around Prague and in the mountains near the borders, where the ski resorts are. Putting aside the central areas for a bit, the explanation of underprediction in mountains is relatively straightforward. The education data are linked to the residents of each municipality. The people who voted in a municipality do not necessarily need to match with residents. It is known that more affluent population groups, who are more likely to go to a ski resort, voted overwhelmingly for Pavel. And since the elections were in winter, a lot of them likely voted in ski resorts, affecting the outcome of the model.</p>
<p>The overpredicted areas, on the other hand, are known for higher levels of deprivation, which may have played a role in the results. What is clear, is that geography plays a huge role in the modelling of the elections.</p>
</section>
</section>
<section id="spatial-heterogeneity" class="level2">
<h2 class="anchored" data-anchor-id="spatial-heterogeneity">Spatial heterogeneity</h2>
<p>Not all areas behave equally, it seems that some systematically vote for Pavel more than for Babiš while others vote for him less. You need to account for this when building a regression model. One way is by capturing <em>spatial heterogeneity</em>. It implicitly assumes that the outcome of the model spatially varies. You can expect <span class="math inline">\(\alpha\)</span> to vary across space, or individual values of <span class="math inline">\(\beta\)</span>. Spatial fixed effects capture the former.</p>
<section id="spatial-fixed-effects" class="level3">
<h3 class="anchored" data-anchor-id="spatial-fixed-effects">Spatial fixed effects</h3>
<p>You need to find a way to let <span class="math inline">\(\alpha\)</span> change across space. One option is through the proxy variable capturing higher-level geography. You have information about <em>okres</em> (the closest translation to English would probably be district or county) each municipality belongs to. Let’s start by checking if that could be useful by visualising residuals within each. While you can use the box plot directly, it may be better to sort the values by median residuals, so let’s complicate the code a bit.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="annotated-cell-17"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-17-1" class="code-annotation-target"><a href="#annotated-cell-17-1" aria-hidden="true" tabindex="-1"></a>medians <span class="op">=</span> (</span>
<span id="annotated-cell-17-2"><a href="#annotated-cell-17-2" aria-hidden="true" tabindex="-1"></a>    elections_data.groupby(<span class="st">"okres"</span>)</span>
<span id="annotated-cell-17-3"><a href="#annotated-cell-17-3" aria-hidden="true" tabindex="-1"></a>    .residual.median()</span>
<span id="annotated-cell-17-4"><a href="#annotated-cell-17-4" aria-hidden="true" tabindex="-1"></a>    .to_frame(<span class="st">"okres_residual"</span>)</span>
<span id="annotated-cell-17-5"><a href="#annotated-cell-17-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-17-6"><a href="#annotated-cell-17-6" aria-hidden="true" tabindex="-1"></a>f, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">6</span>))</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-17-7" class="code-annotation-target"><a href="#annotated-cell-17-7" aria-hidden="true" tabindex="-1"></a>sns.boxplot(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-17-8" class="code-annotation-target"><a href="#annotated-cell-17-8" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>elections_data.merge(</span>
<span id="annotated-cell-17-9"><a href="#annotated-cell-17-9" aria-hidden="true" tabindex="-1"></a>        medians, how<span class="op">=</span><span class="st">"left"</span>, left_on<span class="op">=</span><span class="st">"okres"</span>, right_index<span class="op">=</span><span class="va">True</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-17-10" class="code-annotation-target"><a href="#annotated-cell-17-10" aria-hidden="true" tabindex="-1"></a>    ).sort_values(<span class="st">"okres_residual"</span>),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-17-11" class="code-annotation-target"><a href="#annotated-cell-17-11" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"okres"</span>,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="6" onclick="event.preventDefault();">6</a><span id="annotated-cell-17-12" class="code-annotation-target"><a href="#annotated-cell-17-12" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"residual"</span>,</span>
<span id="annotated-cell-17-13"><a href="#annotated-cell-17-13" aria-hidden="true" tabindex="-1"></a>)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-17" data-target-annotation="7" onclick="event.preventDefault();">7</a><span id="annotated-cell-17-14" class="code-annotation-target"><a href="#annotated-cell-17-14" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> plt.xticks(rotation<span class="op">=</span><span class="dv">90</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-17" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1,2,3,4,5" data-code-cell="annotated-cell-17">Get median residual value per <em>okres</em> using <code>groupby</code> and convert the resulting <code>Series</code> to <code>DataFrame</code> to be able to merge it with the original data.</span>
</dd>
<dt data-target-cell="annotated-cell-17" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="7" data-code-cell="annotated-cell-17">Create a box plot and pass the data.</span>
</dd>
<dt data-target-cell="annotated-cell-17" data-target-annotation="3">3</dt>
<dd>
<span data-code-annotation="3" data-code-lines="8,9" data-code-cell="annotated-cell-17">The data is the <code>elections_data</code> table merged with the <code>medians</code> that are after merge stored as the <code>"okres_residual"</code> column.</span>
</dd>
<dt data-target-cell="annotated-cell-17" data-target-annotation="4">4</dt>
<dd>
<span data-code-annotation="4" data-code-lines="10" data-code-cell="annotated-cell-17">Sort by the <code>"okres_residual"</code> column.</span>
</dd>
<dt data-target-cell="annotated-cell-17" data-target-annotation="5">5</dt>
<dd>
<span data-code-annotation="5" data-code-lines="11" data-code-cell="annotated-cell-17">The x value should represent each <em>okres</em>.</span>
</dd>
<dt data-target-cell="annotated-cell-17" data-target-annotation="6">6</dt>
<dd>
<span data-code-annotation="6" data-code-lines="12" data-code-cell="annotated-cell-17">The y value should represent residuals.</span>
</dd>
<dt data-target-cell="annotated-cell-17" data-target-annotation="7">7</dt>
<dd>
<span data-code-annotation="7" data-code-lines="14" data-code-cell="annotated-cell-17">Rotate x tick labels by 90 degrees for readability.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-18-output-1.png" width="1265" height="638" class="figure-img"></p>
<figcaption class="figure-caption">Distributions of residuals by okres</figcaption>
</figure>
</div>
</div>
</div>
<p>There are clear differences among these geographies, with a gradient between median -16.5 and 8.3. In a model that does not show spatial heterogeneity across higher-level geographies like these, all medians would be close to zero. This is positive information as it indicates, that we can encode these geographies in the model as a spatial proxy. Using <code>statsmodels</code>, you can adapt the equation and include <code>"okres"</code> as a dummy variable.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="annotated-cell-18"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-18" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-18-1" class="code-annotation-target"><a href="#annotated-cell-18-1" aria-hidden="true" tabindex="-1"></a>formula_fe <span class="op">=</span> <span class="ss">f"PetrPavel ~ </span><span class="sc">{</span><span class="st">' + '</span><span class="sc">.</span>join(independent_names)<span class="sc">}</span><span class="ss"> + okres - 1"</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-18" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-18-2" class="code-annotation-target"><a href="#annotated-cell-18-2" aria-hidden="true" tabindex="-1"></a>ols_fe <span class="op">=</span> sm.ols(formula_fe, data<span class="op">=</span>elections_data).fit()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-18" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-18">Add <code>+ okres - 1</code>, where <code>- 1</code> means that you’re fitting a model without an intercept. Since you are now including a categorical variable <em>okres</em>, that will be converted to a dummy one, <code>statsmodels</code> would otherwise drop the first level (<em>okres</em>) to use as a reference represented by the intercept. The resulting coefficients would then reflect the difference between the intercept and the value for each <em>okres</em>. By omitting the intercept, the coefficient can be directly interpreted as <span class="math inline">\(\alpha\)</span>.</span>
</dd>
<dt data-target-cell="annotated-cell-18" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2" data-code-cell="annotated-cell-18">Fit the OLS model using the new formula.</span>
</dd>
</dl>
</div>
</div>
<p>Since every unique value in the <code>"okres"</code> column is now treated as a unique variable the summary is a bit longer than before.</p>
<div class="cell explore" data-execution_count="19">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ols_fe.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>PetrPavel</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.571</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.565</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>92.21</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Mon, 20 Nov 2023</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>22:24:34</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-21472.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>6254</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>4.312e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>6164</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>4.373e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>89</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Benešov]</td>
<td>2.5515</td>
<td>0.725</td>
<td>3.520</td>
<td>0.000</td>
<td>1.131</td>
<td>3.972</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Beroun]</td>
<td>4.3517</td>
<td>0.834</td>
<td>5.219</td>
<td>0.000</td>
<td>2.717</td>
<td>5.986</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Blansko]</td>
<td>-1.0237</td>
<td>0.723</td>
<td>-1.416</td>
<td>0.157</td>
<td>-2.441</td>
<td>0.393</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Brno-město]</td>
<td>-3.6810</td>
<td>7.473</td>
<td>-0.493</td>
<td>0.622</td>
<td>-18.331</td>
<td>10.968</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Brno-venkov]</td>
<td>1.9413</td>
<td>0.593</td>
<td>3.276</td>
<td>0.001</td>
<td>0.779</td>
<td>3.103</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Bruntál]</td>
<td>-10.4042</td>
<td>0.938</td>
<td>-11.094</td>
<td>0.000</td>
<td>-12.243</td>
<td>-8.566</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Břeclav]</td>
<td>1.2036</td>
<td>0.957</td>
<td>1.258</td>
<td>0.209</td>
<td>-0.673</td>
<td>3.080</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Cheb]</td>
<td>-2.6902</td>
<td>1.204</td>
<td>-2.234</td>
<td>0.026</td>
<td>-5.051</td>
<td>-0.330</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Chomutov]</td>
<td>-7.3448</td>
<td>1.145</td>
<td>-6.417</td>
<td>0.000</td>
<td>-9.589</td>
<td>-5.101</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Chrudim]</td>
<td>0.5374</td>
<td>0.744</td>
<td>0.722</td>
<td>0.470</td>
<td>-0.921</td>
<td>1.996</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Domažlice]</td>
<td>-0.5435</td>
<td>0.880</td>
<td>-0.618</td>
<td>0.537</td>
<td>-2.268</td>
<td>1.181</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Děčín]</td>
<td>-4.6916</td>
<td>1.061</td>
<td>-4.424</td>
<td>0.000</td>
<td>-6.771</td>
<td>-2.613</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Frýdek-Místek]</td>
<td>-7.5664</td>
<td>0.907</td>
<td>-8.345</td>
<td>0.000</td>
<td>-9.344</td>
<td>-5.789</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Havlíčkův Brod]</td>
<td>0.3325</td>
<td>0.717</td>
<td>0.464</td>
<td>0.643</td>
<td>-1.073</td>
<td>1.738</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Hodonín]</td>
<td>0.5302</td>
<td>0.845</td>
<td>0.628</td>
<td>0.530</td>
<td>-1.126</td>
<td>2.187</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Hradec Králové]</td>
<td>-0.0895</td>
<td>0.755</td>
<td>-0.119</td>
<td>0.906</td>
<td>-1.570</td>
<td>1.391</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Jablonec nad Nisou]</td>
<td>9.3049</td>
<td>1.275</td>
<td>7.300</td>
<td>0.000</td>
<td>6.806</td>
<td>11.804</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Jeseník]</td>
<td>-7.5762</td>
<td>1.537</td>
<td>-4.930</td>
<td>0.000</td>
<td>-10.589</td>
<td>-4.564</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Jihlava]</td>
<td>5.8273</td>
<td>0.701</td>
<td>8.311</td>
<td>0.000</td>
<td>4.453</td>
<td>7.202</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Jindřichův Hradec]</td>
<td>2.4094</td>
<td>0.749</td>
<td>3.218</td>
<td>0.001</td>
<td>0.942</td>
<td>3.877</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Jičín]</td>
<td>1.7354</td>
<td>0.735</td>
<td>2.362</td>
<td>0.018</td>
<td>0.295</td>
<td>3.176</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Karlovy Vary]</td>
<td>0.3530</td>
<td>1.027</td>
<td>0.344</td>
<td>0.731</td>
<td>-1.661</td>
<td>2.367</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Karviná]</td>
<td>-15.8537</td>
<td>1.819</td>
<td>-8.716</td>
<td>0.000</td>
<td>-19.419</td>
<td>-12.288</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Kladno]</td>
<td>1.9768</td>
<td>0.771</td>
<td>2.564</td>
<td>0.010</td>
<td>0.465</td>
<td>3.488</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Klatovy]</td>
<td>-1.2087</td>
<td>0.791</td>
<td>-1.528</td>
<td>0.126</td>
<td>-2.759</td>
<td>0.342</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Kolín]</td>
<td>2.9124</td>
<td>0.809</td>
<td>3.602</td>
<td>0.000</td>
<td>1.327</td>
<td>4.498</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Kroměříž]</td>
<td>-4.4764</td>
<td>0.859</td>
<td>-5.212</td>
<td>0.000</td>
<td>-6.160</td>
<td>-2.793</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Kutná Hora]</td>
<td>-0.5966</td>
<td>0.819</td>
<td>-0.728</td>
<td>0.466</td>
<td>-2.202</td>
<td>1.009</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Liberec]</td>
<td>2.7545</td>
<td>0.988</td>
<td>2.788</td>
<td>0.005</td>
<td>0.817</td>
<td>4.691</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Litoměřice]</td>
<td>-0.6300</td>
<td>0.751</td>
<td>-0.838</td>
<td>0.402</td>
<td>-2.103</td>
<td>0.843</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Louny]</td>
<td>-10.6715</td>
<td>0.916</td>
<td>-11.655</td>
<td>0.000</td>
<td>-12.466</td>
<td>-8.877</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Mladá Boleslav]</td>
<td>4.5057</td>
<td>0.708</td>
<td>6.361</td>
<td>0.000</td>
<td>3.117</td>
<td>5.894</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Most]</td>
<td>-9.2808</td>
<td>1.479</td>
<td>-6.275</td>
<td>0.000</td>
<td>-12.180</td>
<td>-6.381</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Mělník]</td>
<td>5.0893</td>
<td>0.917</td>
<td>5.548</td>
<td>0.000</td>
<td>3.291</td>
<td>6.888</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Nový Jičín]</td>
<td>-4.1418</td>
<td>1.032</td>
<td>-4.013</td>
<td>0.000</td>
<td>-6.165</td>
<td>-2.119</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Nymburk]</td>
<td>3.9077</td>
<td>0.825</td>
<td>4.734</td>
<td>0.000</td>
<td>2.290</td>
<td>5.526</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Náchod]</td>
<td>8.7053</td>
<td>0.866</td>
<td>10.055</td>
<td>0.000</td>
<td>7.008</td>
<td>10.403</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Olomouc]</td>
<td>-2.8127</td>
<td>0.779</td>
<td>-3.613</td>
<td>0.000</td>
<td>-4.339</td>
<td>-1.286</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Opava]</td>
<td>-7.1956</td>
<td>0.871</td>
<td>-8.261</td>
<td>0.000</td>
<td>-8.903</td>
<td>-5.488</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Ostrava-město]</td>
<td>-9.5847</td>
<td>2.088</td>
<td>-4.590</td>
<td>0.000</td>
<td>-13.679</td>
<td>-5.491</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Pardubice]</td>
<td>0.5159</td>
<td>0.729</td>
<td>0.708</td>
<td>0.479</td>
<td>-0.914</td>
<td>1.945</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Pelhřimov]</td>
<td>2.2828</td>
<td>0.709</td>
<td>3.221</td>
<td>0.001</td>
<td>0.894</td>
<td>3.672</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Plzeň-jih]</td>
<td>-1.2318</td>
<td>0.772</td>
<td>-1.595</td>
<td>0.111</td>
<td>-2.745</td>
<td>0.282</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Plzeň-město]</td>
<td>1.2374</td>
<td>1.939</td>
<td>0.638</td>
<td>0.523</td>
<td>-2.565</td>
<td>5.039</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Plzeň-sever]</td>
<td>2.3828</td>
<td>0.775</td>
<td>3.074</td>
<td>0.002</td>
<td>0.863</td>
<td>3.902</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Prachatice]</td>
<td>3.5268</td>
<td>0.943</td>
<td>3.739</td>
<td>0.000</td>
<td>1.678</td>
<td>5.376</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Praha]</td>
<td>1.5703</td>
<td>7.475</td>
<td>0.210</td>
<td>0.834</td>
<td>-13.082</td>
<td>16.223</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Praha-východ]</td>
<td>7.3812</td>
<td>0.764</td>
<td>9.657</td>
<td>0.000</td>
<td>5.883</td>
<td>8.880</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Praha-západ]</td>
<td>8.0313</td>
<td>0.914</td>
<td>8.791</td>
<td>0.000</td>
<td>6.240</td>
<td>9.822</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Prostějov]</td>
<td>-4.1691</td>
<td>0.780</td>
<td>-5.345</td>
<td>0.000</td>
<td>-5.698</td>
<td>-2.640</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Písek]</td>
<td>3.7584</td>
<td>0.881</td>
<td>4.267</td>
<td>0.000</td>
<td>2.032</td>
<td>5.485</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Přerov]</td>
<td>-8.5036</td>
<td>0.751</td>
<td>-11.324</td>
<td>0.000</td>
<td>-9.976</td>
<td>-7.031</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Příbram]</td>
<td>4.5529</td>
<td>0.707</td>
<td>6.442</td>
<td>0.000</td>
<td>3.168</td>
<td>5.938</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Rakovník]</td>
<td>-0.9709</td>
<td>0.840</td>
<td>-1.156</td>
<td>0.248</td>
<td>-2.617</td>
<td>0.675</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Rokycany]</td>
<td>-0.4692</td>
<td>0.924</td>
<td>-0.508</td>
<td>0.612</td>
<td>-2.281</td>
<td>1.343</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Rychnov nad Kněžnou]</td>
<td>4.6060</td>
<td>0.857</td>
<td>5.376</td>
<td>0.000</td>
<td>2.927</td>
<td>6.285</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Semily]</td>
<td>10.9303</td>
<td>0.952</td>
<td>11.484</td>
<td>0.000</td>
<td>9.065</td>
<td>12.796</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Sokolov]</td>
<td>-4.3738</td>
<td>1.235</td>
<td>-3.542</td>
<td>0.000</td>
<td>-6.795</td>
<td>-1.953</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Strakonice]</td>
<td>1.0393</td>
<td>0.729</td>
<td>1.427</td>
<td>0.154</td>
<td>-0.389</td>
<td>2.468</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Svitavy]</td>
<td>3.0370</td>
<td>0.724</td>
<td>4.195</td>
<td>0.000</td>
<td>1.618</td>
<td>4.456</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Tachov]</td>
<td>-3.5208</td>
<td>1.078</td>
<td>-3.266</td>
<td>0.001</td>
<td>-5.634</td>
<td>-1.408</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Teplice]</td>
<td>-6.0731</td>
<td>1.296</td>
<td>-4.686</td>
<td>0.000</td>
<td>-8.614</td>
<td>-3.532</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Trutnov]</td>
<td>8.9034</td>
<td>0.881</td>
<td>10.106</td>
<td>0.000</td>
<td>7.176</td>
<td>10.630</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Tábor]</td>
<td>5.0145</td>
<td>0.736</td>
<td>6.809</td>
<td>0.000</td>
<td>3.571</td>
<td>6.458</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Třebíč]</td>
<td>0.1759</td>
<td>0.614</td>
<td>0.286</td>
<td>0.775</td>
<td>-1.027</td>
<td>1.379</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Uherské Hradiště]</td>
<td>0.8108</td>
<td>0.866</td>
<td>0.936</td>
<td>0.349</td>
<td>-0.887</td>
<td>2.508</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Vsetín]</td>
<td>2.7505</td>
<td>0.990</td>
<td>2.779</td>
<td>0.005</td>
<td>0.810</td>
<td>4.691</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Vyškov]</td>
<td>-2.5157</td>
<td>0.859</td>
<td>-2.929</td>
<td>0.003</td>
<td>-4.200</td>
<td>-0.832</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Zlín]</td>
<td>3.6748</td>
<td>0.804</td>
<td>4.571</td>
<td>0.000</td>
<td>2.099</td>
<td>5.251</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Znojmo]</td>
<td>-5.4760</td>
<td>0.658</td>
<td>-8.320</td>
<td>0.000</td>
<td>-6.766</td>
<td>-4.186</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Ústí nad Labem]</td>
<td>-5.6362</td>
<td>1.566</td>
<td>-3.598</td>
<td>0.000</td>
<td>-8.707</td>
<td>-2.565</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Ústí nad Orlicí]</td>
<td>6.9769</td>
<td>0.725</td>
<td>9.621</td>
<td>0.000</td>
<td>5.555</td>
<td>8.398</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Česká Lípa]</td>
<td>-1.2302</td>
<td>1.007</td>
<td>-1.222</td>
<td>0.222</td>
<td>-3.204</td>
<td>0.743</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[České Budějovice]</td>
<td>3.5436</td>
<td>0.741</td>
<td>4.781</td>
<td>0.000</td>
<td>2.091</td>
<td>4.996</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Český Krumlov]</td>
<td>6.8514</td>
<td>1.118</td>
<td>6.129</td>
<td>0.000</td>
<td>4.660</td>
<td>9.043</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">okres[Šumperk]</td>
<td>-3.4085</td>
<td>0.865</td>
<td>-3.941</td>
<td>0.000</td>
<td>-5.104</td>
<td>-1.713</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">okres[Žďár nad Sázavou]</td>
<td>5.2729</td>
<td>0.603</td>
<td>8.750</td>
<td>0.000</td>
<td>4.092</td>
<td>6.454</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">without_education</td>
<td>0.5102</td>
<td>0.081</td>
<td>6.303</td>
<td>0.000</td>
<td>0.351</td>
<td>0.669</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">undetermined</td>
<td>0.2195</td>
<td>0.038</td>
<td>5.821</td>
<td>0.000</td>
<td>0.146</td>
<td>0.293</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">incomplete_primary_education</td>
<td>0.0568</td>
<td>0.105</td>
<td>0.542</td>
<td>0.588</td>
<td>-0.149</td>
<td>0.262</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">lower_secondary_and_secondary_education</td>
<td>0.2739</td>
<td>0.013</td>
<td>21.706</td>
<td>0.000</td>
<td>0.249</td>
<td>0.299</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">further_education</td>
<td>0.7216</td>
<td>0.102</td>
<td>7.040</td>
<td>0.000</td>
<td>0.521</td>
<td>0.922</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">post_maturita_studies</td>
<td>1.1008</td>
<td>0.178</td>
<td>6.167</td>
<td>0.000</td>
<td>0.751</td>
<td>1.451</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">bachelors_degree</td>
<td>1.2063</td>
<td>0.082</td>
<td>14.732</td>
<td>0.000</td>
<td>1.046</td>
<td>1.367</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">doctoral_degree</td>
<td>0.7880</td>
<td>0.199</td>
<td>3.956</td>
<td>0.000</td>
<td>0.398</td>
<td>1.179</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">masters_degree</td>
<td>1.1071</td>
<td>0.033</td>
<td>33.305</td>
<td>0.000</td>
<td>1.042</td>
<td>1.172</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">higher_vocational_education</td>
<td>1.0217</td>
<td>0.120</td>
<td>8.547</td>
<td>0.000</td>
<td>0.787</td>
<td>1.256</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">higher_vocational_education_in_a_conservatory</td>
<td>2.5918</td>
<td>0.504</td>
<td>5.148</td>
<td>0.000</td>
<td>1.605</td>
<td>3.579</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">primary_education</td>
<td>0.2144</td>
<td>0.030</td>
<td>7.243</td>
<td>0.000</td>
<td>0.156</td>
<td>0.272</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">complete_secondary_vocational_education</td>
<td>0.8318</td>
<td>0.028</td>
<td>29.208</td>
<td>0.000</td>
<td>0.776</td>
<td>0.888</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">complete_secondary_general_education</td>
<td>0.8074</td>
<td>0.034</td>
<td>23.538</td>
<td>0.000</td>
<td>0.740</td>
<td>0.875</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>286.683</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>1.974</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.000</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>766.532</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>0.226</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>3.55e-167</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>4.655</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>2.52e+18</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.<br>[2] The smallest eigenvalue is 2.09e-30. This might indicate that there are<br>strong multicollinearity problems or that the design matrix is singular.
</div>
</div>
<p>The coefficients for each of the values of the categorical variable <code>"okres"</code> are considered spatial fixed effects. You can extract just those from the model by getting the <code>.params</code> <code>Series</code> and filtering it.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="annotated-cell-20"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-20" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-20-1" class="code-annotation-target"><a href="#annotated-cell-20-1" aria-hidden="true" tabindex="-1"></a>fixed_effects <span class="op">=</span> ols_fe.params.<span class="bu">filter</span>(like<span class="op">=</span><span class="st">"okres"</span>)</span>
<span id="annotated-cell-20-2"><a href="#annotated-cell-20-2" aria-hidden="true" tabindex="-1"></a>fixed_effects.head()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-20" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-20"><code>ols_fe.params</code> is a <code>pandas.Series</code> that can be filtered based on the index using the <code>filter()</code> method.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>okres[Benešov]        2.551453
okres[Beroun]         4.351734
okres[Blansko]       -1.023745
okres[Brno-město]    -3.681027
okres[Brno-venkov]    1.941320
dtype: float64</code></pre>
</div>
</div>
<p>You can see that if you want to join this Series to the original DataFrame, you need to extract the names of each <em>okres</em> from within the square brackets.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="annotated-cell-21"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-21" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-21-1" class="code-annotation-target"><a href="#annotated-cell-21-1" aria-hidden="true" tabindex="-1"></a>fixed_effects.index <span class="op">=</span> fixed_effects.index.<span class="bu">str</span>.strip(</span>
<span id="annotated-cell-21-2"><a href="#annotated-cell-21-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"okres["</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-21" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-21-3" class="code-annotation-target"><a href="#annotated-cell-21-3" aria-hidden="true" tabindex="-1"></a>).<span class="bu">str</span>.strip(<span class="st">"]"</span>)</span>
<span id="annotated-cell-21-4"><a href="#annotated-cell-21-4" aria-hidden="true" tabindex="-1"></a>fixed_effects.head()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-21" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-21">Use the <code>.str</code> accessor that enables you to use string methods on a Series and <em>strip</em> the strings of the specified characters.</span>
</dd>
<dt data-target-cell="annotated-cell-21" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="3" data-code-cell="annotated-cell-21">Use it again to strip the closing bracket.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>Benešov        2.551453
Beroun         4.351734
Blansko       -1.023745
Brno-město    -3.681027
Brno-venkov    1.941320
dtype: float64</code></pre>
</div>
</div>
<p>The resulting Series can be merged with the <code>elections_data</code>, allowing us to map the spatial fixed effects.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="annotated-cell-22"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-22-1" class="code-annotation-target"><a href="#annotated-cell-22-1" aria-hidden="true" tabindex="-1"></a>max_effect <span class="op">=</span> fixed_effects.<span class="bu">abs</span>().<span class="bu">max</span>()</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-22-2" class="code-annotation-target"><a href="#annotated-cell-22-2" aria-hidden="true" tabindex="-1"></a>elections_data.merge(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-22-3" class="code-annotation-target"><a href="#annotated-cell-22-3" aria-hidden="true" tabindex="-1"></a>    fixed_effects.to_frame(<span class="st">"fixed_effect"</span>),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-22-4" class="code-annotation-target"><a href="#annotated-cell-22-4" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"okres"</span>,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-22-5" class="code-annotation-target"><a href="#annotated-cell-22-5" aria-hidden="true" tabindex="-1"></a>    right_index<span class="op">=</span><span class="va">True</span>,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="6" onclick="event.preventDefault();">6</a><span id="annotated-cell-22-6" class="code-annotation-target"><a href="#annotated-cell-22-6" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span>,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="7" onclick="event.preventDefault();">7</a><span id="annotated-cell-22-7" class="code-annotation-target"><a href="#annotated-cell-22-7" aria-hidden="true" tabindex="-1"></a>).plot(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-22" data-target-annotation="8" onclick="event.preventDefault();">8</a><span id="annotated-cell-22-8" class="code-annotation-target"><a href="#annotated-cell-22-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"fixed_effect"</span>, legend<span class="op">=</span><span class="va">True</span>, vmin<span class="op">=-</span>max_effect, vmax<span class="op">=</span>max_effect, cmap<span class="op">=</span><span class="st">"PRGn"</span></span>
<span id="annotated-cell-22-9"><a href="#annotated-cell-22-9" aria-hidden="true" tabindex="-1"></a>).set_axis_off()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-22" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-22">Identify the maximum fixed effect value based on absolute value to specify <code>vmin</code> and <code>vmax</code> values of the colormap.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2" data-code-cell="annotated-cell-22">Merge the <code>fixed_effects</code> to <code>elections_data</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="3">3</dt>
<dd>
<span data-code-annotation="3" data-code-lines="3" data-code-cell="annotated-cell-22">Merge requires a <code>DataFrame</code>, so convert it to one with a column named <code>"fixed_effect"</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="4">4</dt>
<dd>
<span data-code-annotation="4" data-code-lines="4" data-code-cell="annotated-cell-22">Use the column <code>"okres"</code> from <code>elections_data</code> as a merge key.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="5">5</dt>
<dd>
<span data-code-annotation="5" data-code-lines="5" data-code-cell="annotated-cell-22">Use the index of <code>fixed_effects</code> as a merge key.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="6">6</dt>
<dd>
<span data-code-annotation="6" data-code-lines="6" data-code-cell="annotated-cell-22">Use the left join, keeping the structure of <code>elections_data</code> intact.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="7">7</dt>
<dd>
<span data-code-annotation="7" data-code-lines="7" data-code-cell="annotated-cell-22">Plot the <code>"fixed_effect"</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-22" data-target-annotation="8">8</dt>
<dd>
<span data-code-annotation="8" data-code-lines="8" data-code-cell="annotated-cell-22">Use <code>max_effect</code> to specify the extent of the colormap to ensure it had mid-point at 0.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-23-output-1.png" width="518" height="389" class="figure-img"></p>
<figcaption class="figure-caption">Fixed effect per okres</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Spatial regimes and spatial dependence
</div>
</div>
<div class="callout-body-container callout-body">
<p>Where spatial fixed effects allow <span class="math inline">\(\alpha\)</span> to change geographically (within each <em>okres</em>), spatial regimes allow <span class="math inline">\(\beta_k\)</span> to change within the same regions. Spatial regimes cannot be done within <code>statsmodels</code> as they require more specialised treatment offered by the <code>spreg</code> package. Check the <a href="https://geographicdata.science/book/notebooks/11_regression.html#spatial-regimes">Spatial regimes</a> sections of the<a href="https://geographicdata.science/book/notebooks/11_regression.html"><em>Spatial Regression</em></a> chapter from the Geographic Data Science with Python by <span class="citation" data-cites="rey2023geographic">Rey, Arribas-Bel, and Wolf (<a href="#ref-rey2023geographic" role="doc-biblioref">2023</a>)</span> for more details.</p>
<p>The same chapter also covers the modelling of spatial dependence using <code>spreg</code>. Both are considered advanced usage within this course but feel free to read through the materials yourself.</p>
</div>
</div>
<p>With spatial fixed effects, you were able to include spatial dimension in the model through a proxy variable, resulting in an improvement of adjusted <span class="math inline">\(R^2\)</span> from 0.422 to 0.565 while also extracting the fixed effect of each <em>okres</em>. However, the model is still global. We are not able to determine how explanatory is education composition regionally.</p>
</section>
</section>
<section id="geographically-weighted-regression" class="level2">
<h2 class="anchored" data-anchor-id="geographically-weighted-regression">Geographically weighted regression</h2>
<p>Geographically Weighted Regression (GWR) overcomes the limitation of the OLS, which provides a single global estimate by examining how the relationship between a dependent variable and independent variable changes across different geographic locations. It does this by moving a search window through the dataset, defining regions around each regression point, and fitting a regression model to the data within each region. This process is repeated for all the sample points in the dataset, resulting in localized estimates. These local estimates can then be mapped to visualize variations in variable relationships at different locations. However, for a dataset with 6254 observations, like the one used here, GWR will fit 6254 weighted regression models. That can eventually pose a limitation when dealing with larger datasets, for which fitting the GWR can take too long.</p>
<p>Visually, you can imagine a spatial kernel being constructed around each location (point, specifically) where the kernel function defines its shape and bandwidth its size, as illustrated in <a href="#fig-kernels">Figure&nbsp;1</a>.</p>
<div id="fig-kernels" class="quarto-layout-panel">
<figure class="figure">
<div class="quarto-layout-row quarto-layout-valign-bottom">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-bandwidth" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/bandwidth.png" class="img-fluid figure-img" data-ref-parent="fig-kernels"></p>
<figcaption class="figure-caption">(a) Illustration of bandwidth and its relation to weight.</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-kernel" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/fixed_bandwidth.png" class="img-fluid figure-img" data-ref-parent="fig-kernels"></p>
<figcaption class="figure-caption">(b) Illustration of two spatial kernels across a point pattern.</figcaption>
</figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Illustrations of kernels. Reproduced from Fotheringham et al. <span class="citation" data-cites="fotheringham2002geographically">(<a href="#ref-fotheringham2002geographically" role="doc-biblioref">2002, 44–45</a>)</span></figcaption><p></p>
</figure>
</div>
<p>With kernels being the core of the GWR method, their specification significantly affects the resulting model. You can specify three parameters:</p>
<ul>
<li><strong>Kernel shape</strong>: The shape of the curve formed by the kernel. In <code>mgwr</code> package used here, <code>"bisquare"</code>, <code>"gaussian"</code>, and <code>"exponential"</code> kernels are supported.</li>
<li><strong>Kernel size</strong>: The bandwidth distance specifying how large is the moving window.</li>
<li><strong>Bandwidth adaptivity</strong>: Bandwidth can be either fixed, specified by the metric distance, where the moving window is essentially formed as a buffer around a point, or adaptive, specified by the number of nearest neighbours.</li>
</ul>
<p>The details of the implications of the choices are beyond the scope of this lesson but are discussed in-depth by <span class="citation" data-cites="fotheringham2002geographically">Fotheringham, Brunsdon, and Charlton (<a href="#ref-fotheringham2002geographically" role="doc-biblioref">2002</a>)</span>.</p>
<section id="fixed-bandwidth" class="level3">
<h3 class="anchored" data-anchor-id="fixed-bandwidth">Fixed bandwidth</h3>
<p>The method can be illustrated on a GWR using a fixed bandwidth and the default bi-square kernel.</p>
<section id="bandwidth-selection" class="level4">
<h4 class="anchored" data-anchor-id="bandwidth-selection">Bandwidth selection</h4>
<p>You may have some theoretically defined bandwidth (e.g.&nbsp;you know that you want to consider only locations closer than 25 km) or use cross-validation to find the optimal bandwidth programmatically. CV can be an expensive procedure as the selection procedure fits models based on different bandwidths and compares residuals to choose the one where those are minimised. <code>mgwr</code> has the <code>mgwr.sel_bw.Sel_BW</code> function that helps you with the search. But before using it (or any other <code>mgwr</code> function), you need to prepare the data in the correct form.</p>
<p>As mentioned above, the GWR assumes point locations as those are well-defined within the distance search (unlike polygons), so you need to extract centroids from geometries and get their coordinates.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="annotated-cell-23"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-23" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-23-1" class="code-annotation-target"><a href="#annotated-cell-23-1" aria-hidden="true" tabindex="-1"></a>coords <span class="op">=</span> elections_data.centroid.get_coordinates().values</span>
<span id="annotated-cell-23-2"><a href="#annotated-cell-23-2" aria-hidden="true" tabindex="-1"></a>coords</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-23" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-23">Create centroids, extract their coordinates and the underlying numpy array instead of a DataFrame.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>array([[ -850410.51852285,  -994320.67123109],
       [ -593313.18017394, -1149911.22029507],
       [ -749835.86565295, -1163643.97264363],
       ...,
       [ -643316.42508618, -1080131.19290794],
       [ -681632.98081662, -1178150.00416665],
       [ -757365.40441225, -1083270.55289191]])</code></pre>
</div>
</div>
<p>Since <code>mgwr</code> is designed to work with numpy objects rather than pandas, extract both dependent and independent variables as arrays.</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="annotated-cell-24"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-24" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-24-1" class="code-annotation-target"><a href="#annotated-cell-24-1" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> elections_data[<span class="ss">f"PetrPavel"</span>].values.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-24" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-24-2" class="code-annotation-target"><a href="#annotated-cell-24-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> elections_data[independent_names[<span class="dv">1</span>:]].values</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-24" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-24">Get a column, extract its numpy representation and reshape it to an expected shape. The array should be two-dimensional.</span>
</dd>
<dt data-target-cell="annotated-cell-24" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2" data-code-cell="annotated-cell-24">Get a subset of columns and their array. Notice the omission of the first independent variable (<code>[1:]</code>). Unlike <code>statsmodels</code>, <code>mgwr</code> is not able to automatically deal with the interaction effects of independent variables while having an intercept. You therefore drop the first category and use the intercept in its place.</span>
</dd>
</dl>
</div>
</div>
<p>With the data ready, you can identify the optimal bandwidth. This step may take some time (probably minutes).</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="annotated-cell-25"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-25" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-25-1" class="code-annotation-target"><a href="#annotated-cell-25-1" aria-hidden="true" tabindex="-1"></a>sel_bw <span class="op">=</span> mgwr.sel_bw.Sel_BW(coords, y, X, fixed<span class="op">=</span><span class="va">True</span>)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-25" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-25-2" class="code-annotation-target"><a href="#annotated-cell-25-2" aria-hidden="true" tabindex="-1"></a>bw <span class="op">=</span> sel_bw.search()</span>
<span id="annotated-cell-25-3"><a href="#annotated-cell-25-3" aria-hidden="true" tabindex="-1"></a>bw</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-25" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-25">Pass in coordinates, an array with dependent variable, an array with independent variables, and specify that you want a fixed bandwidth (in meters).</span>
</dd>
<dt data-target-cell="annotated-cell-25" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2" data-code-cell="annotated-cell-25">Initiate the search routine.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/home/runner/micromamba/envs/sds/lib/python3.11/site-packages/spglm/iwls.py:37: LinAlgWarning: Ill-conditioned matrix (rcond=3.94411e-21): result may not be accurate.
  xtx_inv_xt = linalg.solve(xtx, xT)
/home/runner/micromamba/envs/sds/lib/python3.11/site-packages/spglm/iwls.py:37: LinAlgWarning: Ill-conditioned matrix (rcond=3.33013e-22): result may not be accurate.
  xtx_inv_xt = linalg.solve(xtx, xT)
/home/runner/micromamba/envs/sds/lib/python3.11/site-packages/spglm/iwls.py:37: LinAlgWarning: Ill-conditioned matrix (rcond=8.5851e-21): result may not be accurate.
  xtx_inv_xt = linalg.solve(xtx, xT)
/home/runner/micromamba/envs/sds/lib/python3.11/site-packages/spglm/iwls.py:37: LinAlgWarning: Ill-conditioned matrix (rcond=8.12331e-20): result may not be accurate.
  xtx_inv_xt = linalg.solve(xtx, xT)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>34168.16</code></pre>
</div>
</div>
<p>The optimal fixed bandwidth seems to be a bit more than 34 kilometres. You can pass it to the <code>GWR</code> function and fit the regression.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="annotated-cell-26"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-26-1"><a href="#annotated-cell-26-1" aria-hidden="true" tabindex="-1"></a>fixed_bandwidth <span class="op">=</span> mgwr.gwr.GWR(</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-26" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-26-2" class="code-annotation-target"><a href="#annotated-cell-26-2" aria-hidden="true" tabindex="-1"></a>    coords, y, X, bw<span class="op">=</span>bw, fixed<span class="op">=</span><span class="va">True</span>, name_x<span class="op">=</span>independent_names[<span class="dv">1</span>:]</span>
<span id="annotated-cell-26-3"><a href="#annotated-cell-26-3" aria-hidden="true" tabindex="-1"></a>)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-26" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-26-4" class="code-annotation-target"><a href="#annotated-cell-26-4" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> fixed_bandwidth.fit()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-26" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="2" data-code-cell="annotated-cell-26">Pass the data and bandwidth, specify that the bandwidth is fixed and optionally pass the names of each independent variable to be used in the report.</span>
</dd>
<dt data-target-cell="annotated-cell-26" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="4" data-code-cell="annotated-cell-26">Fit the regression and save its results.</span>
</dd>
</dl>
</div>
</div>
<p>As before, you can use a summary method.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>results.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>===========================================================================
Model type                                                         Gaussian
Number of observations:                                                6254
Number of covariates:                                                    14

Global Regression Results
---------------------------------------------------------------------------
Residual sum of squares:                                         472435.355
Log-likelihood:                                                  -22397.315
AIC:                                                              44822.630
AICc:                                                             44824.707
BIC:                                                             417891.662
R2:                                                                   0.423
Adj. R2:                                                              0.422

Variable                              Est.         SE  t(Est/SE)    p-value
------------------------------- ---------- ---------- ---------- ----------
Intercept                           36.341      9.252      3.928      0.000
undetermined                        -0.174      0.104     -1.676      0.094
incomplete_primary_education        -0.450      0.171     -2.632      0.008
lower_secondary_and_secondary_      -0.073      0.093     -0.786      0.432
further_education                    0.604      0.147      4.114      0.000
post_maturita_studies                0.991      0.223      4.433      0.000
bachelors_degree                     0.801      0.131      6.124      0.000
doctoral_degree                      0.860      0.237      3.624      0.000
masters_degree                       0.761      0.099      7.699      0.000
higher_vocational_education          1.369      0.160      8.539      0.000
higher_vocational_education_in       2.404      0.584      4.117      0.000
primary_education                   -0.290      0.101     -2.878      0.004
complete_secondary_vocational_       0.506      0.097      5.197      0.000
complete_secondary_general_edu       0.450      0.100      4.485      0.000

Geographically Weighted Regression (GWR) Results
---------------------------------------------------------------------------
Spatial kernel:                                          Fixed bisquare
Bandwidth used:                                                   34168.160

Diagnostic information
---------------------------------------------------------------------------
Residual sum of squares:                                         247794.379
Effective number of parameters (trace(S)):                          828.144
Degree of freedom (n - trace(S)):                                  5425.856
Sigma estimate:                                                       6.758
Log-likelihood:                                                  -20379.457
AIC:                                                              42417.202
AICc:                                                             42671.010
BIC:                                                              48006.443
R2:                                                                   0.698
Adjusted R2:                                                          0.651
Adj. alpha (95%):                                                     0.001
Adj. critical t value (95%):                                          3.339

Summary Statistics For GWR Parameter Estimates
---------------------------------------------------------------------------
Variable                   Mean        STD        Min     Median        Max
-------------------- ---------- ---------- ---------- ---------- ----------
Intercept                15.048    111.553   -764.931     29.497    627.385
undetermined              0.094      1.214     -5.521     -0.038      8.143
incomplete_primary_e     -0.001      1.522     -6.462      0.065      7.177
lower_secondary_and_      0.146      1.142     -6.693     -0.003      7.762
further_education         0.560      1.611     -8.310      0.371     12.760
post_maturita_studie      0.873      1.685     -8.284      0.776      9.729
bachelors_degree          1.067      1.341    -10.368      0.969     11.842
doctoral_degree           1.021      2.252    -14.086      0.976     20.897
masters_degree            1.006      1.104     -3.303      0.899      7.815
higher_vocational_ed      1.085      1.548     -5.055      0.942     12.725
higher_vocational_ed      2.294      4.616    -20.167      2.498     32.132
primary_education         0.116      1.189     -7.042     -0.050      8.594
complete_secondary_v      0.624      1.180     -4.729      0.460      7.852
complete_secondary_g      0.616      1.131     -4.232      0.449      8.692
===========================================================================
</code></pre>
</div>
</div>
<p>The function fits GWR but also OLS for comparison and prints its results under the Global Regression Results section. You can see that the performance matches the first model done with <code>statsmodels</code> above. The performance of the GWR based on the adjusted <span class="math inline">\(R^2\)</span> is 0.651, another improvement over the fixed effects OLS model. It is probably as good as it can be given the data on education can explain only a part of the election behaviour.</p>
<p>Apart from the global <span class="math inline">\(R^2\)</span>, GWR can report <span class="math inline">\(R^2\)</span> per geometry, giving us further insights into where education is the driver of the election result and where you need to look for other causes.</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="annotated-cell-28"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-28" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-28-1" class="code-annotation-target"><a href="#annotated-cell-28-1" aria-hidden="true" tabindex="-1"></a>elections_data[<span class="st">"local_r2"</span>] <span class="op">=</span> results.localR2</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-28" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-28-2" class="code-annotation-target"><a href="#annotated-cell-28-2" aria-hidden="true" tabindex="-1"></a>elections_data.plot(<span class="st">"local_r2"</span>, legend<span class="op">=</span><span class="va">True</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">1</span>).set_axis_off()</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-28" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-28">Extract the array of local <span class="math inline">\(R^2\)</span> and assign it as a column.</span>
</dd>
<dt data-target-cell="annotated-cell-28" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2" data-code-cell="annotated-cell-28">Plot the values on a map. The theoretical minimum is 0 and the maximum is 1.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-29-output-1.png" width="511" height="402" class="figure-img"></p>
<figcaption class="figure-caption">Local <span class="math inline">\(R^2\)</span></figcaption>
</figure>
</div>
</div>
</div>
<p>Higher local <span class="math inline">\(R^2\)</span> means that the model is able to use the data at each municipality and its surrounding areas to provide a result that is closer to the actual observed gain of Petr Pavel.</p>
<p>You can use the new GWR model and compare its predicted results with the OLS done first and the actual results.</p>
<div class="cell" data-execution_count="29">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>f, axs <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">14</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>elections_data.plot(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    ols.predict(elections_data), legend<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, ax<span class="op">=</span>axs[<span class="dv">0</span>]</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>elections_data.plot(</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    results.predy.flatten(), legend<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">100</span>, ax<span class="op">=</span>axs[<span class="dv">1</span>]</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>).set_axis_off()</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>elections_data.plot(</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PetrPavel"</span>, legend<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">100</span>, ax<span class="op">=</span>axs[<span class="dv">2</span>]</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_title(<span class="st">"OLS prediction"</span>)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_title(<span class="st">"GWR prediction"</span>)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">2</span>].set_title(<span class="st">"Actual results"</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_axis_off()</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_axis_off()</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">2</span>].set_axis_off()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-30-output-1.png" width="512" height="1062" class="figure-img"></p>
<figcaption class="figure-caption">OLS prediction, GWR prediction, and the actual outcome</figcaption>
</figure>
</div>
</div>
</div>
<p>It is clear that the model is getting closer. Notice especially the mountains in the southwest and north of the country. You can check this even better by plotting residuals.</p>
<div class="cell" data-execution_count="30">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>f, axs <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">8</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>elections_data.plot(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residual"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">"RdBu"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    vmin<span class="op">=-</span>max_residual,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    vmax<span class="op">=</span>max_residual,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>axs[<span class="dv">0</span>],</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>elections_data.plot(</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    results.resid_response.flatten(),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">"RdBu"</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    vmin<span class="op">=-</span>max_residual,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    vmax<span class="op">=</span>max_residual,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    ax<span class="op">=</span>axs[<span class="dv">1</span>],</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_title(<span class="st">"OLS residuals"</span>)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_title(<span class="st">"GWR residuals"</span>)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_axis_off()</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">1</span>].set_axis_off()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-31-output-1.png" width="513" height="630" class="figure-img"></p>
<figcaption class="figure-caption">OLS residuals and GWR residuals</figcaption>
</figure>
</div>
</div>
</div>
<p>Apart from localised <span class="math inline">\(R^2\)</span>, GWR also contains localised <span class="math inline">\(\beta_k\)</span> coefficients. While you can plot them directly (they are available as <code>results.params</code>), you should also understand whether the coefficients are statistically significant. For that, you first need to understand what is the critical value of <span class="math inline">\(t\)</span>. It is reported in the summary above but not available as an attribute.</p>
<p>The <code>results</code> object contains the adjusted alpha values for 0.1, 0.05 and 0.01 levels of significance:</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>results.adj_alpha</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>array([1.69052693e-03, 8.45263464e-04, 1.69052693e-05])</code></pre>
</div>
</div>
<p>You can use the selected alpha value together with the <code>results.critical_tval()</code> method to get the critical value of <span class="math inline">\(t\)</span>.</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="annotated-cell-32"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><a class="code-annotation-anchor" data-target-cell="annotated-cell-32" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-32-1" class="code-annotation-target"><a href="#annotated-cell-32-1" aria-hidden="true" tabindex="-1"></a>sig95 <span class="op">=</span> results.adj_alpha[<span class="dv">1</span>]</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-32" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-32-2" class="code-annotation-target"><a href="#annotated-cell-32-2" aria-hidden="true" tabindex="-1"></a>critical_t <span class="op">=</span> results.critical_tval(alpha<span class="op">=</span>sig95)</span>
<span id="annotated-cell-32-3"><a href="#annotated-cell-32-3" aria-hidden="true" tabindex="-1"></a>critical_t</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-32" data-target-annotation="1">1</dt>
<dd>
<span data-code-annotation="1" data-code-lines="1" data-code-cell="annotated-cell-32">Select 0.05 level of significance.</span>
</dd>
<dt data-target-cell="annotated-cell-32" data-target-annotation="2">2</dt>
<dd>
<span data-code-annotation="2" data-code-lines="2" data-code-cell="annotated-cell-32">Derive <span class="math inline">\(t\)</span>.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>3.339151343631635</code></pre>
</div>
</div>
<p>If a coefficient estimate has an absolute value of <span class="math inline">\(t\)</span> greater than 3.33, then it is statistically significant. You can use this level to mask out the coefficients on the maps below making a distinction between significant and non-significant values.</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>significant <span class="op">=</span> np.<span class="bu">abs</span>(results.tvalues) <span class="op">&gt;</span> critical_t</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">4</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">9</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>axs <span class="op">=</span> axs.flatten()</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, name <span class="kw">in</span> <span class="bu">enumerate</span>(independent_names[<span class="dv">1</span>:<span class="op">-</span><span class="dv">1</span>]):</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    significant_mask <span class="op">=</span> significant[:, i <span class="op">+</span> <span class="dv">1</span>]</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    elections_data.plot(results.params[:, i <span class="op">+</span> <span class="dv">1</span>], cmap<span class="op">=</span><span class="st">"plasma"</span>, ax<span class="op">=</span>axs[i])</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    elections_data[<span class="op">~</span>significant_mask].plot(color<span class="op">=</span><span class="st">"white"</span>, ax<span class="op">=</span>axs[i], alpha<span class="op">=</span><span class="fl">.9</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    axs[i].set_title(name[:<span class="dv">20</span>], fontdict<span class="op">=</span>{<span class="st">'fontsize'</span>: <span class="dv">8</span>})</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    axs[i].set_axis_off()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hands_on_files/figure-html/cell-34-output-1.png" width="689" height="677" class="figure-img"></p>
<figcaption class="figure-caption">Local coefficients</figcaption>
</figure>
</div>
</div>
</div>
<p>It seems that the coefficients are significant only in some areas, so you need to be careful when drawing conclusions here. This can be due to a lack of relationship or a small sample size. Try for yourself how the significance changes if you increase the bandwidth. But be careful as too large a bandwidth may miss regional differences and a bandwidth that would cover the whole country would be equal to the OLS model.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Adaptive bandwidth
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you’d like to use the adaptive bandwidth, you can use same tools. Just specify <code>fixed=False</code> in both <code>Sel_BW</code> and <code>GWR</code>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode py code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>sel_bw <span class="op">=</span> mgwr.sel_bw.Sel_BW(coords, y, X, fixed<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>bw <span class="op">=</span> sel_bw.search()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode py code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>adaptive <span class="op">=</span> mgwr.gwr.GWR(coords, y, X, bw<span class="op">=</span>bw, fixed<span class="op">=</span><span class="va">False</span>, name_x<span class="op">=</span>independent_names[<span class="dv">1</span>:])</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>results_adaptive <span class="op">=</span> adaptive.fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Additional reading
</div>
</div>
<div class="callout-body-container callout-body">
<p>Have a look at the chapter <a href="https://geographicdata.science/book/notebooks/11_regression.html#spatial-regimes"><em>Spatial Regression</em></a> from the Geographic Data Science with Python by <span class="citation" data-cites="rey2023geographic">Rey, Arribas-Bel, and Wolf (<a href="#ref-rey2023geographic" role="doc-biblioref">2023</a>)</span> for more details and some other extensions.</p>
<p>If you’d like to learn the details of GWR, <em>Geographically Weighted Regression</em> by <span class="citation" data-cites="fotheringham2002geographically">Fotheringham, Brunsdon, and Charlton (<a href="#ref-fotheringham2002geographically" role="doc-biblioref">2002</a>)</span> is a good start.</p>
</div>
</div>
</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="acknowledgements" class="level2 appendix"><h2 class="anchored quarto-appendix-heading">Acknowledgements</h2><div class="quarto-appendix-contents">

<p>The first part of this section loosely follows the <em>Spatial Regression</em> chapter from the <em>Geographic Data Science with Python</em> by <span class="citation" data-cites="rey2023geographic">Rey, Arribas-Bel, and Wolf (<a href="#ref-rey2023geographic" role="doc-biblioref">2023</a>)</span>. The section of GWR is inspired by the <em>Spatial Modelling for Data Scientists</em> course by <span class="citation" data-cites="Rowe2023spatial">Rowe and Arribas-Bel (<a href="#ref-Rowe2023spatial" role="doc-biblioref">2023</a>)</span>.</p>



</div></section><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-fotheringham2002geographically" class="csl-entry" role="listitem">
Fotheringham, A Stewart, Chris Brunsdon, and Martin Charlton. 2002. <em>Geographically Weighted Regression: The Analysis of Spatially Varying Relationships</em>. John Wiley &amp; Sons.
</div>
<div id="ref-rey2023geographic" class="csl-entry" role="listitem">
Rey, Sergio, Dani Arribas-Bel, and Levi John Wolf. 2023. <em>Geographic Data Science with Python</em>. Chapman &amp; Hall/CRC Texts in Statistical Science. London, England: Taylor &amp; Francis.
</div>
<div id="ref-Rowe2023spatial" class="csl-entry" role="listitem">
Rowe, Francisco, and Daniel Arribas-Bel. 2023. <span>“Spatial Modelling for Data Scientists.”</span> https://smds-book.github.io/smds/.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapter_10/concepts.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Relationship and prediction</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapter_10/exercise.html" class="pagination-link">
        <span class="nav-page-text">Fit that model</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Course material by <a href="https://martinfleischmann.net">Martin Fleischmann</a>. Available under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>