---
title: "Does it correlate?"
format: html
---

In this part, you will try to explore spatial autocorrelation on your own.

## Scottish Index of Multiple Deprivation again

In the [exercise on `pandas`](../data_wrangling/exercise.qmd), you have worked with the
Scottish Index of Multiple Deprivation (SIMD). Since you learned how to work with spatial
data later, there was no geometry assigned. That will change today.

1. Download the ESRI Shapefile version of the Scottish Index of Multiple Deprivation 2020 from [this link](https://spatialdata.gov.scot/geonetwork/srv/eng/catalog.search#/metadata/02866b0b-66e5-46ab-9b1c-d433dc3c2fae).
2. Read it as a `GeoDataFrame` and assign a column you think would be the best as an index.

::: {.callout-note collapse="true"}
# Backup data

If the link does not work, please [report it](https://github.com/martinfleis/sds/issues/new) and use the [backup](https://martinfleischmann.net/sds/autocorrelation/data/SG_SIMD_2020.zip).
:::

3. Filter the data to work only with Glasgow.
4. Create contiguity weights based on the reduced dataset.

## Global spatial autocorrelation

With the data prepared like this:

### Join Counts

- Create a binary variable from `"Rankv2"` encoding areas with rank above city-wide mean.
- Measure Join Counts statistic on your new variable.
- *What conclusions can you reach from the Join Counts?*

### Moran's $I$

- Visualise the main `"Rankv2"` with a Moran Plot
- Calculate Moran's $I$
- *What conclusions can you reach from the Moran Plot and Moran's I? What's the main spatial pattern? Does it agree with Join counts?*

## Local spatial autocorrelation

Now that you have a good sense of the overall pattern in the SIMD dataset, let's move to the local scale:

- Calculate LISA statistics for the areas
- Make a map of significant clusters at the 5%
- *Can you identify hotspots or coldspots? If so, what do they mean? What about spatial outliers?*

::: {.callout-warning}
The last action is a bit more sophisticated, put all your brain power into it and you'll achieve it!
:::

- Create cluster maps for significance levels 1% and 10%; compare them with the one we obtained. *What are the main changes? Why?*
- Can you create both interactive and static versions of those maps?

## Acknowledgements {.appendix}

This section is derived from _A Course on Geographic Data Science_ by
@darribas_gds_course, licensed under CC-BY-SA 4.0. The text was slightly adapted
to accommodate a different dataset and the inclusion of Join counts.