---
title: Does it correlate?
jupyter: sds
---



Here is one way of getting the solution. There are others, feel free to share yours.


```py
import geopandas as gpd
import esda
import matplotlib.pyplot as plt
import seaborn as sns

from libpysal import graph
```

Read it as a `GeoDataFrame` and assign a column you think would be the best as an index.

```py
simd = gpd.read_file("https://maps.gov.scot/ATOM/shapefiles/SG_SIMD_2020.zip")
simd = simd.set_index("DataZone")
```

Filter the data to work only with Glasgow.

If you check the Excel file in the zip above, you will learn that a column LAName represents Local Authority name. You can use it to filter Glasgow.

Since the string may be something else than "Glasgow", let's find out the right one. You can list all unique names in the LAName column.

```py
simd.LAName.unique()
```

From that you can see that the right string is 'Glasgow City'. You can use that directly. But if you'd like to know the programmatic way (you can ask chatGPT to explain the code if you need):

```py
glasgow_name = simd.LAName[simd.LAName.str.contains('Glasgow')].unique()[0]
glasgow_name
```

```py
glasgow = simd[simd.LAName == "Glasgow City"]
```

Create contiguity weights based on the reduced dataset.

```py
contiguity = graph.Graph.build_contiguity(glasgow)
```

Create a binary variable from `"Rankv2"` encoding areas with rank above city-wide mean.

```py
mean_rank = glasgow["Rankv2"].mean()
glasgow["better_half"] = glasgow["Rankv2"] > mean_rank
```

Measure Join Counts statistic on your new variable.

```py
jc = esda.Join_Counts(
    glasgow["better_half"],
    contiguity,
)
```

Let's print the results i a nice way. Using a multi-line f-string (google!):

```py
print(f"""BB: {jc.bb}
WW: {jc.ww}
BW: {jc.bw}
J: {jc.J}
mean BB: {jc.mean_bb}
mean BW: {jc.mean_bw}
p_sim BB: {jc.p_sim_bb}
""")
```

Visualise the main `"Rankv2"` with a Moran Plot

```py
glasgow['rank_std'] = (
    glasgow["Rankv2"] - glasgow["Rankv2"].mean()
) / glasgow["Rankv2"].std()
```

```py
contiguity_r = contiguity.transform("r")

glasgow['rank_lag'] = contiguity_r.lag(glasgow['rank_std'])
```

```py
f, ax = plt.subplots(figsize=(6, 6))
sns.regplot(
    x="rank_std",
    y="rank_lag",
    data=glasgow,
    marker=".",
    scatter_kws={"alpha": 0.2},
    line_kws=dict(color="lightcoral")
)
ax.axvline(0, c="black", alpha=0.5)
ax.axhline(0, c="black", alpha=0.5)
```

Calculate Moran's $I$

```py
mi = esda.Moran(glasgow['rank_std'], contiguity_r)
```

```py
mi.I
```

```py
mi.p_sim
```

Calculate LISA statistics for the areas

```py
lisa = esda.Moran_Local(glasgow['rank_std'], contiguity_r)
```

Make a map of significant clusters at the 5%

```py
lisa.explore(glasgow)
```

Create cluster maps for significance levels 1%

```py
lisa.explore(glasgow, crit_value=.01)
```

Create cluster maps for significance levels 10%;

```py
lisa.explore(glasgow, crit_value=.1)
```

- Create a single map that combines all three significance levels and changes the alpha to distinguish them.
- Can you create both interactive and static versions of those maps?

You can use a trick of simply overlaying them.

```py
m = lisa.explore(glasgow, crit_value=.1, tiles="CartoDB Positron")
lisa.explore(glasgow, m=m)
lisa.explore(glasgow, crit_value=.01, m=m)
```

But that probably won't cut it in most cases. So it is time for a composed multi-layer plot.

```py
glasgow["labels_001"] = lisa.get_cluster_labels(0.01)
glasgow["labels_005"] = lisa.get_cluster_labels()
glasgow["labels_01"] = lisa.get_cluster_labels(0.1)


ax = glasgow.loc[(glasgow["labels_01"] == "High-High")].plot(color="#d7191c", alpha=.25)
glasgow.loc[(glasgow["labels_01"] == "Low-Low")].plot(ax=ax, color="#2c7bb6", alpha=.25)
glasgow.loc[(glasgow["labels_01"] == "Low-High")].plot(ax=ax, color="#abd9e9", alpha=.25)
glasgow.loc[(glasgow["labels_01"] == "High-Low")].plot(ax=ax, color="#fdae61", alpha=.25)

glasgow.loc[(glasgow["labels_005"] == "High-High")].plot(ax=ax, color="#d7191c", alpha=.5)
glasgow.loc[(glasgow["labels_005"] == "Low-Low")].plot(ax=ax, color="#2c7bb6", alpha=.5)
glasgow.loc[(glasgow["labels_005"] == "Low-High")].plot(ax=ax, color="#abd9e9", alpha=.5)
glasgow.loc[(glasgow["labels_005"] == "High-Low")].plot(ax=ax, color="#fdae61", alpha=.5)

glasgow.loc[(glasgow["labels_001"] == "High-High")].plot(ax=ax, color="#d7191c", alpha=1)
glasgow.loc[(glasgow["labels_001"] == "Low-Low")].plot(ax=ax, color="#2c7bb6", alpha=1)
glasgow.loc[(glasgow["labels_001"] == "Low-High")].plot(ax=ax, color="#abd9e9", alpha=1)
glasgow.loc[(glasgow["labels_001"] == "High-Low")].plot(ax=ax, color="#fdae61", alpha=1)
```

Same can be done for interactive mapping.

```py
# m = glasgow.loc[(glasgow["labels_01"] == "High-High")].explore(color="#d7191c", opacity=.8, tiles="CartoDB Positron")
# glasgow.loc[(glasgow["labels_01"] == "Low-Low")].explore(m=m, color="#2c7bb6", opacity=.8)
# glasgow.loc[(glasgow["labels_01"] == "Low-High")].explore(m=m, color="#abd9e9", opacity=.8)
# glasgow.loc[(glasgow["labels_01"] == "High-Low")].explore(m=m, color="#fdae61", opacity=.8)

# glasgow.loc[(glasgow["labels_005"] == "High-High")].explore(m=m, color="#d7191c", opacity=.8)
# glasgow.loc[(glasgow["labels_005"] == "Low-Low")].explore(m=m, color="#2c7bb6", opacity=.8)
# glasgow.loc[(glasgow["labels_005"] == "Low-High")].explore(m=m, color="#abd9e9", opacity=.8)
# glasgow.loc[(glasgow["labels_005"] == "High-Low")].explore(m=m, color="#fdae61", opacity=.8)

# glasgow.loc[(glasgow["labels_001"] == "High-High")].explore(m=m, color="#d7191c", opacity=.8)
# glasgow.loc[(glasgow["labels_001"] == "Low-Low")].explore(m=m, color="#2c7bb6", opacity=.8)
# glasgow.loc[(glasgow["labels_001"] == "Low-High")].explore(m=m, color="#abd9e9", opacity=.8)
# glasgow.loc[(glasgow["labels_001"] == "High-Low")].explore(m=m, color="#fdae61", opacity=.8)
```


