# https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml
on:
  push:
    branches: main

name: Render and Publish

jobs:
    build-deploy:
        name: "Build and deploy"
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash -l {0}
        steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            with:
                tinytex: false

          - name: Setup Pixi
            uses: prefix-dev/setup-pixi@v0.8.5
            with:
              cache: true

          - name: Check and log the environment
            run: |
              pixi run python -c "import geopandas; geopandas.show_versions();"

          - name: Register kernel
            run: |
              pixi run python -m ipykernel install --user --name sds

          - name: Render Book project
            run: |
                pixi run quarto render
                pixi run quarto render --profile micro

          - name: Move subprojects under a single domain
            run: |
                mv _site_micro _site/micro

          - name: Deploy
            uses: peaceiris/actions-gh-pages@v4
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./_site