on:
  schedule:
    - cron: '59 8 * * 1,4'
  workflow_dispatch:
    inputs:
      version:
        description: Manual test execution
        default: Test
        required: false

name: Test execution using Conda

jobs:
    build:
        name: "Build the site"
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-latest, macos-14, windows-latest]
        defaults:
          run:
            shell: bash -l {0}
        steps:
          - name: Check out repository
            uses: actions/checkout@v4

          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            with:
                tinytex: false
                version: pre-release

          - name: Setup micromamba
            uses: mamba-org/setup-micromamba@v2
            with:
              environment-file: environment.yml
              micromamba-version: "latest"

          - name: Check and log the environment
            run: |
              python -c "import geopandas; geopandas.show_versions();"
              micromamba info
              micromamba list

          - name: Register kernel
            run: |
              python -m ipykernel install --user --name sds

          - name: Quarto check
            run: |
              quarto check

          - name: Render Book project
            run: |
                quarto render